print("Enter Roll No.")
roll = int(input())
print("Enter Name")
name = input()
print("Enter Percentage")
per = float(input())
print("Enter Fee")
fee = int(input())
print("Enter Grade")
grade = input()
print("-------------------------------")
print("Name             :",name)
print("Roll No.         :",roll)
print("Fee              :",fee)
print("Percentage       :",per)
print("Grade            :",grade)