print("Enter any decimal No.")
n = int(input())
print("Binary No. of ",n," is ",bin(n))
print("Enter any decimal No.")
n = int(input())
print("Octal No. of ",n," is ",oct(n))
print("Enter any decimal No.")
n = int(input())
print("Hexadecimal No. of ",n," is ",hex(n))